version: '3.7'

services:
  kickerbot:
    container_name: slack-kicker-bot
    image: slackkickerbot:latest
    env_file:
      - .kickerbot.env
    volumes:
      - tokendata:/app_data
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
  proxy:
    container_name: slack-kicker-bot-proxy
    image: autossh:latest
    env_file:
      - .kickerbot.env
    volumes:
      - ${SSH_KEY}:/id_rsa
      - ${KNOWN_HOST}:/known_hosts
    restart: always

volumes:
  tokendata:
    name: kickerbottokenstore