version: '3.7'

services:
  kickerbot:
    container_name: slack-kicker-bot
    image: slackkickerbot:latest
    env_file:
      - .kickerbot.env
    volumes:
      - tokendata:/app_data
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
  serveo:
    container_name: slack-kicker-bot-serveo
    image: taichunmin/serveo:latest
    tty: true
    stdin_open: true
     # see https://serveo.net/ for more options
    env_file:
      - .kickerbot.env
    command: >
      autossh -M 0
      -o ServerAliveInterval=60
      -o ServerAliveCountMax=3
      -o ExitOnForwardFailure=yes
      -o StrictHostKeyChecking=no
      -R 443:kickerbot:8080
      serveo.net
    restart: unless-stopped

volumes:
  tokendata:
    name: kickerbottokenstore