name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build jacocoTestCoverageVerification jacocoTestReport
    - name: Upload Java
      uses: actions/upload-artifact@v1
      with:
        name: javaLib
        path: build/libs/slack-kicker-app-*.jar
    - name: Upload Report
      uses: actions/upload-artifact@v1
      with:
        name: jacocoReport
        path: build/jacocoHtml
